name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-blc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test-blc
      run: |
        sudo apt install -y sbcl
        make test-blc
